//#lne_head [Cp main]
#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 32, local_size_y = 32) in;


layout(set = 2, binding = 0) uniform samplerCube      globalCubemaps[];

layout(set = 2, binding = 1, rgba16f) uniform writeonly image2DArray globalCubemapImages[];

layout(scalar, set = 0, binding = 0) uniform GlobalUBO
{
    mat4 uViewProj;
    mat4 uView;
    mat4 uProj;
    vec3 uEyePos;
    vec3 uSunDir;
};

layout(scalar, set = 1, binding = 0) uniform ComputeParams
{
    float   uPhiDelta;
    float   uThetaDelta;

    uint    tRadianceCubemap;
    uint    tIrradianceCubemap;
};

vec3 uvToDirection(vec2 uv, uint faceIndex)
{
    vec3 dir;
    uv = 2.0 * vec2(uv.x, 1.0 - uv.y) - 1.0;

    switch (faceIndex)
    {
    case 0: // +X
        dir = vec3(1.0, uv.y, -uv.x); break;
    case 1: // -X
        dir = vec3(-1.0, uv.y, uv.x); break;
    case 2: // +Y
        dir = vec3(uv.x, 1.0, -uv.y); break;
    case 3: // -Y
        dir = vec3(uv.x, -1.0, uv.y); break;
    case 4: // +Z
        dir = vec3(uv.x, uv.y, 1.0); break;
    case 5: // -Z
        dir = vec3(-uv.x, uv.y, -1.0); break;
    default:
        dir = vec3(0.0, 0.0, 0.0);
    }
    return normalize(dir);
}

#define PI 3.14159265358979323846

void main()
{
    uvec2 imageDimensions = imageSize(globalCubemapImages[tIrradianceCubemap]).xy;
    if (gl_GlobalInvocationID.x >= imageDimensions.x || gl_GlobalInvocationID.y >= imageDimensions.y)
        return; // out of bounds

    vec2 st = vec2(gl_GlobalInvocationID.xy) / vec2(imageDimensions);
    uint faceIndex = gl_GlobalInvocationID.z;
    vec3 N = uvToDirection(st, faceIndex);

    // https://learnopengl.com/PBR/IBL/Diffuse-irradiance
    vec3 up = mix(vec3(0.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0), step(0.00001, dot(N, vec3(0.0, 1.0, 0.0))));

    vec3 right = normalize(cross(up, N));
    up = normalize(cross(right, N));

    vec3 irradiance = vec3(0.0);
    float nrSamples = 0.0;
    for (float phi = 0.0; phi < 2.0 * PI; phi += uPhiDelta)
    {
        for (float theta = 0.0; theta < 0.5 * PI; theta += uThetaDelta)
        {
            // spherical to cartesian (in tangent space)
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            // tangent space to world
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * N;

            irradiance += texture(globalCubemaps[tRadianceCubemap], sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    imageStore(globalCubemapImages[tIrradianceCubemap], ivec3(gl_GlobalInvocationID.xy, faceIndex), vec4(irradiance, 1.0));
}
