//#lne_head [Cp main]
#version 460

#extension GL_EXT_scalar_block_layout :     enable
#extension GL_EXT_nonuniform_qualifier :    require

//size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

layout(scalar, set=0, binding=0) uniform GlobalUBO {
    mat4 uViewProj;
    mat4 uView;
    mat4 uProj;
    vec3 uEyePos;
    vec3 uSunDir;
};

layout(set = 2, binding = 0) uniform sampler2D      globalTextures[];
layout(set = 2, binding = 0) uniform samplerCube    globalCubemaps[];

layout(set = 2, binding = 1, rgba8) uniform writeonly image2D   globalImageRgba8[];
layout(set = 2, binding = 1, rgba16f) uniform writeonly image2D globalImageRgba16f[];
layout(set = 2, binding = 1, rgba32f) uniform writeonly image2D globalImageRgba32f[];

layout(set = 1, binding = 0) uniform ProgramData {
    vec4 uColor;
    uint tOutput;
};

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(globalImageRgba16f[tOutput]);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

        if(gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
        {
            color.x = float(texelCoord.x)/(size.x);
            color.y = float(texelCoord.y)/(size.y);	
        }
    
        imageStore(globalImageRgba16f[tOutput], texelCoord, color);
    }
}
