//#lne_head [Cp main]
#version 460

#extension GL_EXT_scalar_block_layout :     enable
#extension GL_EXT_nonuniform_qualifier :    require

layout (local_size_x = 32, local_size_y = 32) in;

layout(set = 1, binding = 1, rg16f) uniform writeonly image2D      globalImages[];

float saturate(float x)
{
    return clamp(x, 0.0, 1.0);
}

layout(scalar, set = 0, binding = 0) uniform ComputeParams
{
    uint uNumSamples;
    uint tBRDFLut;
};

#define PI 3.14159265358979323846

float rand(vec2 co)
{
    float a = 12.9898;
    float b = 78.233;
    float c = 43758.5453;
    float dt= dot(co.xy ,vec2(a,b));
    float sn= mod(dt,3.14);
    return fract(sin(sn) * c);
}

// https://holger.dammertz.org/stuff/notes_HammersleyOnHemisphere.html
vec2 Hammersley2D(uint i, uint N)
{
    uint b = i;
    
    b = (b << 16u) | (b >> 16u);
    b = ((b & 0x55555555u) << 1u) | ((b & 0xAAAAAAAAu) >> 1u);
    b = ((b & 0x33333333u) << 2u) | ((b & 0xCCCCCCCCu) >> 2u);
    b = ((b & 0x0F0F0F0Fu) << 4u) | ((b & 0xF0F0F0F0u) >> 4u);
    b = ((b & 0x00FF00FFu) << 8u) | ((b & 0xFF00FF00u) >> 8u);
    
    float radicalInverse = float(b) * 2.3283064365386963e-10;
    return vec2(float(i)/float(N), radicalInverse);
}

// https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf
vec3 ImportanceSampleGGX(vec2 Xi, float alpha, vec3 N)
{
    float Phi = 2.0 * PI * Xi.x + rand(N.xz) * 0.1;
    float CosTheta = sqrt((1.0 - Xi.y) / (1.0 + (alpha * alpha - 1.0) * Xi.y));
    float SinTheta = sqrt(1.0 - CosTheta * CosTheta);
    
    // hammersley sample to hemisphere
    vec3 H;
    H.x = SinTheta * cos(Phi);
    H.y = SinTheta * sin(Phi);
    H.z = CosTheta;

    // tangent space to world space
    vec3 TangentY = cross(N, vec3(0.0, 1.0, 0.0));
	TangentY = mix(cross(N, vec3(1.0, 0.0, 0.0)), TangentY, step(0.00001, dot(TangentY, TangentY)));
	TangentY = normalize(TangentY);
	vec3 TangentX = normalize(cross(N, TangentY));

    // hammersley sample to world space
    return TangentX * H.x + TangentY * H.y + N * H.z;
}

// Schlick-GGX by Schlick & Beckman Geometry Shadowing Function
float SchlickBeckmanGSF(float nDotL, float nDotV, float alpha) {
    float r = (alpha + 1.0);
    float k = (r * r) / 8.0;

    float gL = nDotL / (nDotL * (1.0 - k) + k);
    float gV = nDotV / (nDotV * (1.0 - k) + k);

    return gL * gV;
}

// https://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf
vec2 IntegrateBRDF(float nDotV, float roughness)
{
    vec3 N = vec3(0.0, 0.0, 1.0);
    vec3 V = vec3(sqrt(1.0 - nDotV*nDotV), 0.0, nDotV);
    float alpha = roughness * roughness;

    vec2 lut = vec2(0.0);

    for (uint i = 0; i < uNumSamples; ++i)
    {
        vec2 Xi = Hammersley2D(i, uNumSamples);
        vec3 H = ImportanceSampleGGX(Xi, alpha, N);
        vec3 L = 2.0 * dot(V, H) * H - V;
        float nDotL = saturate(dot(N, L));
        float nDotH = saturate(dot(N, H));
        float vDotH = saturate(dot(V, H));
        float nDotV = saturate(dot(N, V));
        if (nDotL > 0.0)
        {
            float G = SchlickBeckmanGSF(nDotL, nDotV, alpha);
            float G_Vis = G * vDotH / (nDotV * nDotH);
            float Fc = pow(1.0 - vDotH, 5.0);
            lut.x += (1.0 - Fc) * G_Vis;
            lut.y += Fc * G_Vis;
        }
    }
    return lut / float(uNumSamples);
}

void main()
{
    uvec2 imageSize = imageSize(globalImages[tBRDFLut]).xy;
    if (gl_GlobalInvocationID.x >= imageSize.x || gl_GlobalInvocationID.y >= imageSize.y)
        return;

    vec2 uv = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) / vec2(imageSize);
    imageStore(globalImages[tBRDFLut],
        ivec2(gl_GlobalInvocationID.xy),
        vec4(IntegrateBRDF(uv.x, uv.y), 0.0, 1.0)
    );
}
