//#lne_head [Cp main][Tp Compute]
#version 460

#include "Common.glslh"
#include "CommonCompute.glslh"
#include "HDRCompute.glslh"
#include "PBR.glslh"

layout (local_size_x = 32, local_size_y = 32) in;

layout(set = TEX_SET, binding = 1, rg16f) uniform writeonly image2D      globalImages[];

layout(scalar, set = PARAMS_SET, binding = 0) uniform ComputeParams
{
    uint uNumSamples;
    uint tBRDFLut;
};

// https://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf
vec2 IntegrateBRDF(float nDotV, float roughness)
{
    vec3 N = vec3(0.0, 0.0, 1.0);
    vec3 V = vec3(sqrt(1.0 - nDotV*nDotV), 0.0, nDotV);
    float alpha = roughness * roughness;

    vec2 lut = vec2(0.0);

    for (uint i = 0; i < uNumSamples; ++i)
    {
        vec2 Xi = Hammersley2D(i, uNumSamples);
        vec3 H = ImportanceSampleGGX(Xi, alpha, N);
        vec3 L = 2.0 * dot(V, H) * H - V;
        float nDotL = saturate(dot(N, L));
        float nDotH = saturate(dot(N, H));
        float vDotH = saturate(dot(V, H));
        float nDotV = saturate(dot(N, V));
        if (nDotL > 0.0)
        {
            float G = SchlickBeckmanGSF(nDotL, nDotV, alpha);
            float G_Vis = G * vDotH / (nDotV * nDotH);
            float Fc = pow(1.0 - vDotH, 5.0);
            lut.x += (1.0 - Fc) * G_Vis;
            lut.y += Fc * G_Vis;
        }
    }
    return lut / float(uNumSamples);
}

void main()
{
    uvec2 imageSize = imageSize(globalImages[tBRDFLut]).xy;
    if (gl_GlobalInvocationID.x >= imageSize.x || gl_GlobalInvocationID.y >= imageSize.y)
        return;

    vec2 uv = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) / vec2(imageSize);
    imageStore(globalImages[tBRDFLut],
        ivec2(gl_GlobalInvocationID.xy),
        vec4(IntegrateBRDF(uv.x, uv.y), 0.0, 1.0)
    );
}
