//#lne_head [Cp main]
#version 460

#include "Common.glslh"
#include "CommonCompute.glslh"
#include "HDRCompute.glslh"

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = TEX_SET, binding = 0) uniform sampler2D      globalTextures[];

layout(set = TEX_SET, binding = 1, rgba16f) uniform writeonly image2DArray globalCubemaps[];

layout(scalar, set = PARAMS_SET, binding = 0) uniform ComputeParams
{
    uint tHDRTexture;
    uint tCubemapTexture;
};

void main()
{
    vec2 st = vec2(gl_GlobalInvocationID.xy) / vec2(imageSize(globalCubemaps[tCubemapTexture]).xy);
    uint faceIndex = gl_GlobalInvocationID.z;
    vec3 direction = uvToDirection(st, faceIndex);
    // https://en.wikipedia.org/wiki/Spherical_coordinate_system#Cartesian_coordinates
    float phi = atan(direction.z, direction.x);
    float theta = acos(direction.y);
    // Normalize phi to [0, 1] and theta to [0, 1]
    vec2 uv = vec2(phi / (2.0 * PI) + 0.5, theta / PI);
    vec3 color = texture(globalTextures[tHDRTexture], uv).rgb;
    imageStore(globalCubemaps[tCubemapTexture], ivec3(gl_GlobalInvocationID), vec4(color, 1.0));
}
