//#lne_head [Cp main][Tp Compute]
#version 460

#include "Common.glslh"
#include "CommonCompute.glslh"
#include "HDRCompute.glslh"

layout(local_size_x = 32, local_size_y = 32) in;


layout(set = TEX_SET, binding = 0) uniform samplerCube      globalCubemaps[];

layout(set = TEX_SET, binding = 1, rgba16f) uniform writeonly image2DArray globalCubemapImages[];


layout(scalar, set = PARAMS_SET, binding = 0) uniform ComputeParams
{
    float   uPhiDelta;
    float   uThetaDelta;

    uint    tRadianceCubemap;
    uint    tIrradianceCubemap;
};

void main()
{
    uvec2 imageDimensions = imageSize(globalCubemapImages[tIrradianceCubemap]).xy;
    if (gl_GlobalInvocationID.x >= imageDimensions.x || gl_GlobalInvocationID.y >= imageDimensions.y)
        return; // out of bounds

    vec2 st = vec2(gl_GlobalInvocationID.xy) / vec2(imageDimensions);
    uint faceIndex = gl_GlobalInvocationID.z;
    vec3 N = uvToDirection(st, faceIndex);

    // https://learnopengl.com/PBR/IBL/Diffuse-irradiance
    vec3 up = mix(vec3(0.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0), step(0.00001, dot(N, vec3(0.0, 1.0, 0.0))));

    vec3 right = normalize(cross(up, N));
    up = normalize(cross(right, N));

    vec3 irradiance = vec3(0.0);
    float nrSamples = 0.0;
    for (float phi = 0.0; phi < 2.0 * PI; phi += uPhiDelta)
    {
        for (float theta = 0.0; theta < 0.5 * PI; theta += uThetaDelta)
        {
            // spherical to cartesian (in tangent space)
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            // tangent space to world
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * N;

            irradiance += texture(globalCubemaps[tRadianceCubemap], sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    imageStore(globalCubemapImages[tIrradianceCubemap], ivec3(gl_GlobalInvocationID.xy, faceIndex), vec4(irradiance, 1.0));
}
