//#lne_head [Cp main]
#version 460

#include "Common.glslh"
#include "CommonCompute.glslh"
#include "HDRCompute.glslh"
#include "PBR.glslh"

layout (local_size_x = 32, local_size_y = 32) in;


layout(set = TEX_SET, binding = 0) uniform samplerCube      globalCubemaps[];

layout(set = TEX_SET, binding = 1, rgba16f) uniform writeonly image2DArray globalCubemapImages[];

layout(scalar, set = PARAMS_SET, binding = 0) uniform ComputeParams
{
    float   uRoughness;
    uint    uNumSamples;

    uint    tRadianceCubemap;
    uint    tPrefilteredCubemap;
};

vec3 PrefilteredColor(float roughness, vec3 normal, vec3 viewDir)
{
    vec3 specularColor = vec3(0.0);
    float totalWeight = 0.0;
    float alpha = roughness * roughness;
    float envMapDimension = float(textureSize(globalCubemaps[tRadianceCubemap], 0).s);
    for (uint i = 0; i < uNumSamples; ++i)
    {
        vec2 Xi = Hammersley2D(i, uNumSamples);
        vec3 vHalf = ImportanceSampleGGX(Xi, alpha, normal);
        vec3 vLight = 2.0 * dot(viewDir, vHalf) * vHalf - viewDir;

        float nDotL = clamp(dot(normal, vLight), 0.0, 1.0);

        // https://placeholderart.wordpress.com/2015/07/28/implementation-notes-runtime-environment-map-filtering-for-image-based-lighting
        // for fast approximation of the specular color
        if (nDotL > 0.0)
        {
            float nDotH = clamp(dot(normal, vHalf), 0.0, 1.0);
            float vDotH = clamp(dot(viewDir, vHalf), 0.0, 1.0);

            float pdf = TrowbridgeReitzNDF(nDotH, alpha) * nDotH / (4.0 * vDotH) + 0.0001;
            // solid angle of the sample
            float omegaS = 1.0 / (float(uNumSamples) * pdf);
            // solid angle of 1 pixel in the cubemap
            float omegaP = 4.0 * PI / (6.0 * envMapDimension * envMapDimension);

            float mipLevel = roughness == 0.0 ? 0.0 : max(0.5 * log2(omegaS / omegaP) + 1.0, 0.0f);

            specularColor += textureLod(globalCubemaps[tRadianceCubemap], vLight, mipLevel).rgb * nDotL;
            totalWeight += nDotL;
        }
    }
    return totalWeight > 0.0 ? specularColor / totalWeight : vec3(0.0);
}

void main()
{
    uvec2 imageDimensions = imageSize(globalCubemapImages[tPrefilteredCubemap]).xy;
    if (gl_GlobalInvocationID.x >= imageDimensions.x || gl_GlobalInvocationID.y >= imageDimensions.y)
        return; // out of bounds
    vec2 st = vec2(gl_GlobalInvocationID.xy) / vec2(imageDimensions);
    uint faceIndex = gl_GlobalInvocationID.z;
    vec3 direction = uvToDirection(st, faceIndex);
    // the view and the normal are the same for all pixels in the cubemap face
    // because the point of view is the center of the cubemap
    vec3 color = PrefilteredColor(uRoughness, direction, direction);

    imageStore(globalCubemapImages[tPrefilteredCubemap], ivec3(gl_GlobalInvocationID.xy, faceIndex), vec4(color, 1.0));
}
