//#lne_head [Cp main]
#version 460

#extension GL_EXT_scalar_block_layout :     enable
#extension GL_EXT_nonuniform_qualifier :    require

layout (local_size_x = 32, local_size_y = 32) in;


layout(set = 1, binding = 0) uniform samplerCube      globalCubemaps[];

layout(set = 1, binding = 1, rgba16f) uniform writeonly image2DArray globalCubemapImages[];

layout(scalar, set = 0, binding = 0) uniform ComputeParams
{
    float   uRoughness;
    uint    uNumSamples;

    uint    tRadianceCubemap;
    uint    tPrefilteredCubemap;
};

float rand(vec2 co)
{
    float a = 12.9898;
    float b = 78.233;
    float c = 43758.5453;
    float dt= dot(co.xy ,vec2(a,b));
    float sn= mod(dt,3.14);
    return fract(sin(sn) * c);
}

#define PI 3.14159265358979323846

float TrowbridgeReitzNDF(float nDotH, float alpha) {
    float a2 = alpha * alpha;
    float d = (nDotH * nDotH) * (a2 - 1) + 1;
    return a2 / (PI * d * d);
}

// https://holger.dammertz.org/stuff/notes_HammersleyOnHemisphere.html
vec2 Hammersley2D(uint i, uint N)
{
    uint b = i;
    
    b = (b << 16u) | (b >> 16u);
    b = ((b & 0x55555555u) << 1u) | ((b & 0xAAAAAAAAu) >> 1u);
    b = ((b & 0x33333333u) << 2u) | ((b & 0xCCCCCCCCu) >> 2u);
    b = ((b & 0x0F0F0F0Fu) << 4u) | ((b & 0xF0F0F0F0u) >> 4u);
    b = ((b & 0x00FF00FFu) << 8u) | ((b & 0xFF00FF00u) >> 8u);
    
    float radicalInverse = float(b) * 2.3283064365386963e-10;
    return vec2(float(i)/float(N), radicalInverse);
}

// https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf
vec3 ImportanceSampleGGX(vec2 Xi, float alpha, vec3 N)
{
    float Phi = 2.0 * PI * Xi.x + rand(N.xz) * 0.1;
    float CosTheta = sqrt((1.0 - Xi.y) / (1.0 + (alpha * alpha - 1.0) * Xi.y));
    float SinTheta = sqrt(1.0 - CosTheta * CosTheta);
    
    // hammersley sample to hemisphere
    vec3 H;
    H.x = SinTheta * cos(Phi);
    H.y = SinTheta * sin(Phi);
    H.z = CosTheta;

    // tangent space to world space
    vec3 TangentY = cross(N, vec3(0.0, 1.0, 0.0));
	TangentY = mix(cross(N, vec3(1.0, 0.0, 0.0)), TangentY, step(0.00001, dot(TangentY, TangentY)));
	TangentY = normalize(TangentY);
	vec3 TangentX = normalize(cross(N, TangentY));

    // hammersley sample to world space
    return TangentX * H.x + TangentY * H.y + N * H.z;
}

vec3 PrefilteredColor(float roughness, vec3 normal, vec3 viewDir)
{
    vec3 specularColor = vec3(0.0);
    float totalWeight = 0.0;
    float alpha = roughness * roughness;
    float envMapDimension = float(textureSize(globalCubemaps[tRadianceCubemap], 0).s);
    for (uint i = 0; i < uNumSamples; ++i)
    {
        vec2 Xi = Hammersley2D(i, uNumSamples);
        vec3 vHalf = ImportanceSampleGGX(Xi, alpha, normal);
        vec3 vLight = 2.0 * dot(viewDir, vHalf) * vHalf - viewDir;

        float nDotL = clamp(dot(normal, vLight), 0.0, 1.0);

        // https://placeholderart.wordpress.com/2015/07/28/implementation-notes-runtime-environment-map-filtering-for-image-based-lighting
        // for fast approximation of the specular color
        if (nDotL > 0.0)
        {
            float nDotH = clamp(dot(normal, vHalf), 0.0, 1.0);
            float vDotH = clamp(dot(viewDir, vHalf), 0.0, 1.0);

            float pdf = TrowbridgeReitzNDF(nDotH, alpha) * nDotH / (4.0 * vDotH) + 0.0001;
            // solid angle of the sample
            float omegaS = 1.0 / (float(uNumSamples) * pdf);
            // solid angle of 1 pixel in the cubemap
            float omegaP = 4.0 * PI / (6.0 * envMapDimension * envMapDimension);

            float mipLevel = roughness == 0.0 ? 0.0 : max(0.5 * log2(omegaS / omegaP) + 1.0, 0.0f);

            specularColor += textureLod(globalCubemaps[tRadianceCubemap], vLight, mipLevel).rgb * nDotL;
            totalWeight += nDotL;
        }
    }
    return totalWeight > 0.0 ? specularColor / totalWeight : vec3(0.0);
}

vec3 uvToDirection(vec2 uv, uint faceIndex)
{
    vec3 dir;
    uv = 2.0 * vec2(uv.x, 1.0 - uv.y) - 1.0;

    switch (faceIndex)
    {
    case 0: // +X
        dir = vec3( 1.0,  uv.y, -uv.x); break;
    case 1: // -X
        dir = vec3(-1.0,  uv.y,  uv.x); break;
    case 2: // +Y
        dir = vec3( uv.x,  1.0, -uv.y); break;
    case 3: // -Y
        dir = vec3( uv.x, -1.0,  uv.y); break;
    case 4: // +Z
        dir = vec3( uv.x,  uv.y,  1.0); break;
    case 5: // -Z
        dir = vec3(-uv.x,  uv.y, -1.0); break;
    default:
        dir = vec3(0.0, 0.0, 0.0);
    }
    return normalize(dir);
}

void main()
{
    uvec2 imageDimensions = imageSize(globalCubemapImages[tPrefilteredCubemap]).xy;
    if (gl_GlobalInvocationID.x >= imageDimensions.x || gl_GlobalInvocationID.y >= imageDimensions.y)
        return; // out of bounds
    vec2 st = vec2(gl_GlobalInvocationID.xy) / vec2(imageDimensions);
    uint faceIndex = gl_GlobalInvocationID.z;
    vec3 direction = uvToDirection(st, faceIndex);
    // the view and the normal are the same for all pixels in the cubemap face
    // because the point of view is the center of the cubemap
    vec3 color = PrefilteredColor(uRoughness, direction, direction);

    imageStore(globalCubemapImages[tPrefilteredCubemap], ivec3(gl_GlobalInvocationID.xy, faceIndex), vec4(color, 1.0));
}
