name: LNEngineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Vulkan SDK
      uses: sjcobb2022/setup-vulkan-sdk@shaderc
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: 'Vulkan-Headers Vulkan-Loader SPIRV-Headers SPIRV-Cross SPIRV-Tools SPIRV-Reflect Glslang shaderc'
        vulkan-use-cache: true

    - name: Build the project using Premake
      run: |
        Write-Host "Running Premake..."
        cd your_project_root_relative_to_repository
        & "vendor\premake\Binaries\premake5.exe" vs2022
        Write-Host "Premake generation complete."
      shell: pwsh

    - name: Build Debug solution
      run: |
        msbuild LNEngine.sln /p:Configuration=Debug
